### ISSUE TITLE
GitHub Project Automation Shared Workflows Approach

### ISSUE THREAD

**Issue by jarmak-nv** [rapidsai/shared-workflows#163]
# Project Automation - Overview
We use GitHub issues, discussions, and projects to a varying degree for RAPIDS project management. To make the Project experience better, we can automate field values such as status or release based on events occuring to the item. As an example, we can synchronize the status between PRs and their linked issues when an update occurs to the PR automatically.

I'm looking for any and all feedback to see if this approach seems viable. I plan on being the lead to implement/maintain these, but it would be good to get another person who could review them as well so I know that adds some cost to our `shared-workflows` team.

#### Where We Stand Today
I've written [a number of automations](https://github.com/NVIDIA/cccl/tree/main/.github/workflows) for the CCCL team, but they're hard to read/understand, and hard to maintain as well. When thinking about rolling out project automations across RAPIDS, I don't think it's feasible to use a bespoke approach. Enter reusable workflows.

#### Proposed Approach
Not all teams are going to want the same automations, so creating reusable workflows that perform specific tasks isn't my ideal approach. Instead, I'd like to create a number of very basic workflows that we can piece together to create complex project automations.

```
.github/workflows 
├── project-get-item-id
├── project-get-linked-issues
├── project-get-set-single-select-field
├── project-get-set-iteration-field
├── project-get-set-date-field
├── project-get-set-text-numeric-field
```

This would enable workflows similar to below:
```yml
name: Project - Set Sprint

on:
  pull_request_target:
    # We will ensure the sprint is the current sprint when an issue is (re)opened, synchronized, or edited
    types: [opened, synchronize, reopened, edited]

jobs:
  get-pr-project-id:
    permissions:
        contents: read
    uses: rapidsai/shared-workflows/.github/workflows/project-get-item-id.yml@main
    with:
        PROJECT_ID: "PVT_abcd123"
    secrets: inherit
    
  get-and-set-current-sprint-option-id:
    permissions:
          contents: read
    uses: rapidsai/shared-workflows/.github/workflows/project-get-set-iteration-option-id.yml@main
    with:
        ITEM_ID: ${{ needs.get-pr-project-id.outputs.ITEM_ID }}
        FIELD_ID: "PVTIF_abcd123"
        
        # true performs the mutation to update the item as well as outputting the option id
        # default = false
        UPDATE-ITEM: true  
        
        # true performs a secondary reusable workflow: project-get-linked-issues and updates them alongside the PR
        # default = false
        UPDATE-LINKED-ISSUES: true
  secrets: inherit
```

### Reasoning
My intention is that a team can say "I want this field to update on that trigger" and write the automation in an almost block-code way. I could envision this as a GUI similar to Lego Mindstorms/labVIEW almost. It also significantly reduces the amount of work to maintain graphQL api changes, removing any graphQL api calls from our repos except for `shared-workflows`.

This approach will create at least 6 new workflows in this repo, and I could imagine more popping up as either new graphQL/project functionality exists, or a new useage I'm not considering approaches. It would be nice if we could have subdirectories of Actions as I do not want to overrun the folder.
